### ISSUE TITLE
Loading from fastboot3DS v1.2 menu (not keycombo) results in screens being turned off

### ISSUE THREAD

**Issue by GerbilSoft** [profi200/open_agb_firm#8]
Attempting to load open\_agb\_firm from the fastboot3DS v1.2 menu results in the screens being turned off. Presumably it's running, since pressing B shuts the system off, but with the screens off it's rather difficult to do anything.

This does *not* happen if open\_agb\_firm is assigned to a key combo and the key combo is used to boot open_agb_firm. It also doesn't happen if loaded through GodMode9 v1.9.1.

**Comment by profi200** [comment]
Known problem that also happens with Luma and b9s (iirc). It has been fixed by porting the proper screen init code to fastboot3DS. Unsure when but a (fb3DS) release is coming. Until then the fix is already in master in case you can live with recompiling it. Unknown when this will be fixed in Luma.

The problem is it is triggering a panic() but you can't see it with screens off. This is because it receives MCU events it should not be receiving due to bad screen init code in the bootloader/payload loader (whatever you wanna call it).

**Comment by GerbilSoft** [comment]
Makes sense. I'll take a look at building the latest fastboot3DS then.
